# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=140)),
                ('job_addr', models.TextField()),
                ('job_link', models.TextField()),
                ('job_search', models.TextField()),
                ('job_title', models.TextField()),
                ('job_posted', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
