# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170518_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comp_name', models.CharField(max_length=140)),
                ('job_addr', models.TextField()),
                ('job_link', models.TextField()),
                ('job_search', models.TextField()),
                ('job_title', models.TextField()),
                ('job_posted', models.DateTimeField()),
            ],
            options={
                'db_table': 'jobs_job',
                'managed': False,
            },
        ),
    ]
