# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(blank=True, max_length=50, null=True)),
                ('job_addr', models.CharField(blank=True, max_length=50, null=True)),
                ('job_link', models.CharField(blank=True, max_length=50, null=True)),
                ('job_posted', models.CharField(blank=True, max_length=50, null=True)),
                ('job_search', models.CharField(blank=True, max_length=50, null=True)),
                ('job_title', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'job_info',
                'managed': False,
            },
        ),
    ]
