# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'managed': True},
        ),
    ]
