# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170518_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobinfo',
            options={'managed': False},
        ),
    ]
