# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-06 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdb',
            name='date_signed_up',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
