# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-02 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0008_auto_20170527_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindJob',
            fields=[
                ('jobinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.JobInfo')),
                ('today', models.DateField()),
            ],
            bases=('jobs.jobinfo',),
        ),
    ]
