# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-21 01:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('find_job', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='findjob',
            name='jobinfo_ptr',
        ),
        migrations.DeleteModel(
            name='FindJob',
        ),
    ]
